config/routes.rb
Rails.application.routes.draw do 
  get 'users/index'
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registrations: 'companies/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: "jobs#index"
  resources :users, only: [:index]
  resources :companies, only: [:index]
  
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    やりたいことが見つかる、お仕事発見アプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHIGOTOYELLについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'SHIGOTOYELL利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHIGOTOYELLを見る</h2>
      <ul>
        <li><%= link_to 'jobs一覧', "#", class: "footer-link" %></li>
        <li><%# link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>SHIGOTOYELLについて</h2>
      <ul>
        <li><%= link_to 'SHIGOTOYELLガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'SHIGOTOYELLロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("logo.png", class:"logo-white"), "#" %>
  <p>© SHIGOTOYELL</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("logo.png", class:"logo-icon"), "/" %>
    
  </div>
  <div class='nav'>
    
    <ul class='lists-users'>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_session, class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %> 
      <div class="users-list">仕事をお探しの方
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      </div>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% end %>
    </ul>
    <ul class='lists-users'>
      <% if company_signed_in? %>
      <%# deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <li><%= link_to current_company.company_name, company_session_path, class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_company_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
      <div class="users-list">事業主の方
      <li><%= link_to 'ログイン',  new_company_session_path, class: "login" %></li>
      <li><%= link_to '新規登録',  new_company_registration_path, class: "sign-up" %></li>
      </div>
      <%# //deviseを導入できたら、ログインの有無で表示が変わるように分岐しましょう%>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>SHIGOTOYELL利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%# image_tag "logo.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo.png", class:"second-logo"), "/" %>
</header>